### ISSUE TITLE
duplicated location code

### ISSUE THREAD

**Issue by annehulsey** [GNS-Science/nzshm-common-py#3]
Tauranga is listed as TMZ but it should be TRG. This will need a corresponding update in the Default NZ Locations as well.

https://github.com/GNS-Science/nzshm-common-py/blob/0d2f1221217c963b91a7e4d6929781f29c2d32f2/nzshm_common/location/location.py#L33

**Comment by annehulsey** [comment]
@chrisbc once this is fixed I can start using the codes in the .hdf5

**Comment by chrisbc** [comment]
Hi @annehulsey  - yes I'm working on it, but it had to take a back seat to getting API BigInt fix sorted. Sorry!

**Comment by annehulsey** [comment]
@chrisbc Ah, no worries, I just realized that I hadn't tagged you so you mightn't have seen it.

**Comment by chrisbc** [comment]
No porblems @annehulsey  I just merged it to main - so if you update you want version>=1.0.2
