### ISSUE TITLE
Feature/API improvements

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-common-py#38]
Below is a typical use case for commons location functions. We'd like this API be easier to use with:
 - fewer imports
 - functions with docs instead of generic dict API

# Excerpt from Toshi Hazard Store
```
from nzshm_common.grids import load_grid
from nzshm_common.location.code_location import CodedLocation
from nzshm_common import location

nz1_grid = load_grid('NZ_0_1_NB_1_1')
city_locs = [(location.LOCATIONS_BY_ID[key]['latitude'], location.LOCATIONS_BY_ID[key]['longitude'])
    for key in location.LOCATION_LISTS["NZ"]["locations"]]
srwg_locs = [(location.LOCATIONS_BY_ID[key]['latitude'], location.LOCATIONS_BY_ID[key]['longitude'])
    for key in location.LOCATION_LISTS["SRWG214"]["locations"]]
location_list = set(nz1_grid + srwg_locs + city_locs)

# get the 0.1 degree grid locations for all the locations
partition_codes = sorted(set([CodedLocation(lat=loc[0], lon=loc[1], resolution=0.1).code for loc in location_list]))
for partition_code in partition_codes:
    ... etc
```

**Comment by DrCuriosity** [comment]
Things to look at:
- Possibly add an `as_tuple` to CodedLocations.
- Helper function to bring in lists of named tuples into a big list of CodedLocations
- Add another function to do the same thing with grids
- Implement with some examples and help
- Supplementary argument: should be able to specify resolution, but default is 0.001.
- check for a function to get all the location list keys (if there isn't one, implement it)

Proposed signatures:
```py
def get_location_list(location_list_names: list[str]=[], resolution=0.001) -> Iterable[CodedLocation):

def get_location_grid(location_grid_name: str, resolution=0.001) -> Iterable[CodedLocation):
```
