### ISSUE TITLE
Refactor region_grid.get_location_grid to be aware of the RegionGridEntry resolutions

### ISSUE THREAD

**Issue by DrCuriosity** [GNS-Science/nzshm-common-py#44]
In #41, a function has been added to retrieve region grid points as CodedLocation objects, at a specific resolution.

Currently this has the signature:
```py
get_location_grid(location_grid_name: str, resolution: float = DEFAULT_RESOLUTION)
    -> Iterable[CodedLocation]
```
Using a default resolution of 0.001 degrees.

However, the `RegionGridEntry` that the data is loaded from has a "native" resolution:
```py
NZ_0_2_NB_1_1 = RegionGridEntry(
    region_name="NZ",
    resolution=0.2,
    neighbours=1,
    grid=NZ_0_2_nb_1_1(),
    version=1,
)
```

It would be more intuitive to have this value as the default resolution on this function.

### Proposed approach

Alter the signature to make resolution `Optional[float]`.

If it is set, use it; if not, then use `RegionGrid[location_grid_name].resolution` as a default.

Consider logging a warning if the resolution specified when calling is different from the native resolution in ways that the user may care about.

**Comment by chrisdicaprio** [comment]
Warn if `resolution` arg is > `RegionGrid[location_grid_name].resolution`
something like:
```
The requested resolution is lower than the grid resolution and will result in (duplicated locations | fewer locations than expected)
```
with the message tailored to how we decide to implement the function (remove duplicates or not)
