### ISSUE TITLE
Proposal: support externally defined location lists

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-common-py#50]
re  #33   I'm a bit wary of including data in this library that is not NSHM data ( SRWG is  OK i guess, but HB & TP)

Can we have common define data formats, but expect users to have datasets for these cases?

common can read csv file of locations, but we need a place to store / version control lists we re-use. Will also avoid polluting the lib with more locaiton lists.

**Comment by chrisdicaprio** [comment]
we can read locations from csv
